name: project
description: "A new Flutter project."

publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_messaging: ^15.2.3
  google_sign_in: ^6.2.2
  awesome_dialog: ^3.2.1
  flutter_secure_storage: ^9.2.4
  curved_navigation_bar: ^1.0.6
  convex_bottom_bar: ^3.2.0
  google_fonts: ^6.2.1
  http: ^1.3.0
  font_awesome_flutter: ^10.2.0
  carousel_slider: ^5.0.0
  loading_animation_widget: ^1.2.0
  shared_preferences: ^2.5.2
  file_picker: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
