// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuQW0d7q1TeWywtHVEXyYOum1Zihenf1o',
    appId: '1:417083356065:web:5db92f25266dd3794511e0',
    messagingSenderId: '417083356065',
    projectId: 'loginsystem-cba47',
    authDomain: 'loginsystem-cba47.firebaseapp.com',
    storageBucket: 'loginsystem-cba47.firebasestorage.app',
    measurementId: 'G-NH181RQVL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC639E1Jy5S0H2I1NVMONcpuwQez3wiuCc',
    appId: '1:417083356065:android:4d70ecebec39c5fc4511e0',
    messagingSenderId: '417083356065',
    projectId: 'loginsystem-cba47',
    storageBucket: 'loginsystem-cba47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEpe4TuwI3GQ3eLD98Y_7wOz7CzFMQK0I',
    appId: '1:417083356065:ios:2a79ff05daafc9364511e0',
    messagingSenderId: '417083356065',
    projectId: 'loginsystem-cba47',
    storageBucket: 'loginsystem-cba47.firebasestorage.app',
    androidClientId: '417083356065-du9t0mfb1put6jdk1srtq10ui7i6t0q5.apps.googleusercontent.com',
    iosClientId: '417083356065-0dffbpk4lpjvqjbk901h0at8fb19g2sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEpe4TuwI3GQ3eLD98Y_7wOz7CzFMQK0I',
    appId: '1:417083356065:ios:2a79ff05daafc9364511e0',
    messagingSenderId: '417083356065',
    projectId: 'loginsystem-cba47',
    storageBucket: 'loginsystem-cba47.firebasestorage.app',
    androidClientId: '417083356065-du9t0mfb1put6jdk1srtq10ui7i6t0q5.apps.googleusercontent.com',
    iosClientId: '417083356065-0dffbpk4lpjvqjbk901h0at8fb19g2sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuQW0d7q1TeWywtHVEXyYOum1Zihenf1o',
    appId: '1:417083356065:web:82c5b85056350e8c4511e0',
    messagingSenderId: '417083356065',
    projectId: 'loginsystem-cba47',
    authDomain: 'loginsystem-cba47.firebaseapp.com',
    storageBucket: 'loginsystem-cba47.firebasestorage.app',
    measurementId: 'G-HDPQJ8W54R',
  );
}
